import createClient from 'openapi-fetch'
import type { paths } from '@/types/api'
import { api } from './api'

/**
 * Typed Kalmio backend client (KALMIO-387).
 *
 * URL paths and request/response shapes are derived from the backend's OpenAPI
 * spec (regenerated by `pnpm gen:api` → `src/types/api.d.ts`). Typos and stale
 * routes are compile-time errors here, not runtime 500s.
 *
 * Under the hood, HTTP requests are delegated to our existing `axios` instance
 * so the request interceptor (Bearer token from Supabase / passkey JWT,
 * Accept-Language), the response interceptor (sliding refresh via
 * X-Refresh-Token, 401 → expired-session redirect), and all the other
 * cross-cutting auth/observability behaviour continue to apply unchanged.
 *
 * Usage:
 *   const { data, error, response } = await apiClient.GET('/api/plans/calendar/active')
 *   //                                              ^ autocompletes from `paths`
 *
 * For migration, prefer adopting `apiClient` one service file at a time; the
 * legacy `api` axios instance keeps working alongside.
 */

const BASE = import.meta.env.VITE_API_URL ?? ''

export const apiClient = createClient<paths>({
  baseUrl: BASE,
  /**
   * Custom fetch implementation that round-trips through our axios instance.
   * That gives openapi-fetch a standards-compliant fetch surface while letting
   * axios handle auth, error normalisation, and the X-Refresh-Token dance.
   *
   * On axios error we still return a `Response` (with the upstream status) so
   * openapi-fetch's normal `{ data, error, response }` destructure works. The
   * 401 redirect is fired inside axios's own response interceptor, so the
   * promise rejection that reaches us here for a 401 is already past the side
   * effect — we just surface it as a Response so callers can decide what to do.
   */
  fetch: async (request: Request): Promise<Response> => {
    const url = request.url
    const method = request.method.toUpperCase()

    let body: unknown = undefined
    if (method !== 'GET' && method !== 'HEAD') {
      const raw = await request.clone().text()
      if (raw) {
        try { body = JSON.parse(raw) }
        catch { body = raw }
      }
    }

    try {
      const resp = await api.request({
        url,
        method,
        data: body,
        // openapi-fetch wants the raw status; accept everything and let it interpret.
        validateStatus: () => true,
      })
      const responseBody = resp.data === undefined || resp.data === '' ? '' : JSON.stringify(resp.data)
      return new Response(responseBody, {
        status: resp.status,
        headers: { 'content-type': 'application/json' },
      })
    } catch (err: unknown) {
      // Network error or interceptor threw — surface as a 5xx so callers see it.
      const message = err instanceof Error ? err.message : String(err)
      return new Response(JSON.stringify({ error: message }), {
        status: 599,
        headers: { 'content-type': 'application/json' },
      })
    }
  },
})

export type { paths } from '@/types/api'
