/**
 * Persistent shopping list service (KALMIO-374 / C11).
 *
 * Wraps the /api/plans/{planId}/shopping-list/** and
 * /api/shopping-list-items/{id}/** endpoints added by the C11 backend ticket.
 *
 * Idempotency-Key headers are injected by the global Axios interceptor
 * (KALMIO-377 / src/lib/api.ts) when `requestIdempotencyKey: true` is set.
 * The manual UUID generation that existed here has been removed (KALMIO-378).
 */
import { api } from '@/lib/api'
import type {
  PersistentShoppingListResponse,
  PersistentShoppingListItem,
  AdHocShoppingListItemRequest,
} from '@/types'

export const persistentShoppingListService = {
  /**
   * POST /api/plans/{planId}/shopping-list/generate
   *
   * Derives a fresh list from the plan's non-SKIPPED planned meals.
   * Idempotent: calling again replaces the existing list (ADHOC items are lost).
   * Returns 201 with the new list.
   */
  generate: (planId: string): Promise<PersistentShoppingListResponse> =>
    api
      .post<PersistentShoppingListResponse>(`/api/plans/${planId}/shopping-list/generate`)
      .then((r) => r.data),

  /**
   * GET /api/plans/{planId}/shopping-list
   *
   * Returns the current list grouped by category.
   * Returns 404 if no list has been generated yet — callers should catch that.
   */
  getForPlan: (planId: string): Promise<PersistentShoppingListResponse> =>
    api
      .get<PersistentShoppingListResponse>(`/api/plans/${planId}/shopping-list`)
      .then((r) => r.data),

  /**
   * PATCH /api/shopping-list-items/{id}/tick
   *
   * Sets ticked_at = now(). Idempotent.
   * Idempotency-Key is generated by the global Axios interceptor.
   */
  tick: (itemId: string): Promise<PersistentShoppingListItem> =>
    api
      .patch<PersistentShoppingListItem>(`/api/shopping-list-items/${itemId}/tick`, null, {
        requestIdempotencyKey: true,
      })
      .then((r) => r.data),

  /**
   * PATCH /api/shopping-list-items/{id}/untick
   *
   * Sets ticked_at = NULL. Idempotent.
   * Idempotency-Key is generated by the global Axios interceptor.
   */
  untick: (itemId: string): Promise<PersistentShoppingListItem> =>
    api
      .patch<PersistentShoppingListItem>(`/api/shopping-list-items/${itemId}/untick`, null, {
        requestIdempotencyKey: true,
      })
      .then((r) => r.data),

  /**
   * POST /api/plans/{planId}/shopping-list/items
   *
   * Adds a user-supplied ad-hoc item. Returns the created ItemResponse.
   * Idempotency-Key is generated by the global Axios interceptor.
   */
  addAdHocItem: (
    planId: string,
    request: AdHocShoppingListItemRequest,
  ): Promise<PersistentShoppingListItem> =>
    api
      .post<PersistentShoppingListItem>(`/api/plans/${planId}/shopping-list/items`, request, {
        requestIdempotencyKey: true,
      })
      .then((r) => r.data),

  /**
   * DELETE /api/shopping-list-items/{id}
   *
   * Removes an item (PLAN or ADHOC). Returns 204.
   * Idempotency-Key is generated by the global Axios interceptor.
   */
  deleteItem: (itemId: string): Promise<void> =>
    api
      .delete(`/api/shopping-list-items/${itemId}`, { requestIdempotencyKey: true })
      .then(() => undefined),
}
